apiVersion: v1
kind: ConfigMap
metadata:
  name: ezaddonconfig
data:
  bds_k8s_containerrepo: ""
  ezbootstraprepo: "bluedata/"
  ezbootstraptoolsimagename: "hpecp-bootstrap-tools"
  ezbootstraptoolsversion: "0.9"
